version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: ./go-scraper
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./config:/app/config

  dashboard:
    build:
      context: ./go-scraper
      dockerfile: Dockerfile.dashboard
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
