name: job-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - pandas>=2.0.0
  - pip
  - pip:
    - google-generativeai>=0.3.0 